include: package:lints/recommended.yaml

linter:
  rules:
    curly_braces_in_flow_control_structures: false
    only_throw_errors: true
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_relative_imports: true
    use_null_aware_elements: true